pip3 install --user xlrd
pip3 install --user xlutils
pip3 install --user xmltodict
pip3 install --user openpyxl
pip3 install --user xlwt
pip3 install --user enum
pip3 install --user termcolor
pip3 install --user requests
pip3 install --user bs4